//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESUN.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public int IdStudent { get; set; }
        public Nullable<int> IdTopic { get; set; }
        public Nullable<int> Evaluation { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
